### PR TITLE
Add icons

### LINKED ISSUE #6: Fetch and use icons

### PR DESCRIPTION
**Pull request by FrederikBolding**
Fixes #6

### CODE REVIEW

**Review by axljoker03 — APPROVED** [review]
👍👍👍

**Review by axljoker03 — COMMENTED** [review]
🤩thanks

**Review by masive1440 — CHANGES_REQUESTED** [review]
****

**Review by masive1440 — APPROVED** [review]
****

**Comment by jraah555** [comment]
fb/add-icons

**Comment by voanhcung** [comment]
0xf9C001323f9bF58eaf90B23AF831A626d9e8d435

**Pull request merged**
