### PR TITLE
Experiment with details modal

### PR DESCRIPTION
**Pull request by FrederikBolding**

### CODE REVIEW

**Review by BIZZLETONC — APPROVED** [review]

**Review by TDG510 — APPROVED** [review]

**Review by DenisLisica — APPROVED** [review]

**Review by gabygroove11 — APPROVED** [review]

**Comment by BlueGhostxxx** [comment]
`MirchellNeal/remix-contract-deployer-plugin to`

**Comment by BlueGhostxxx** [comment]
`gh repo clone FrederikBolding/chainlist`

**Review by jonesk7734 — APPROVED** [review]
😀

**Review by gatleas17 — APPROVED** [review]

**Review by Hanae1963 — APPROVED** [review]

**Review by Dioliode — APPROVED** [review]
DioX

**Comment by Oliv23ava** [comment]
0xf931a800B8B96453674d78A75D83593432Ae26d4

**Pull request closed without merging**
